// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOQauHtjpvSJHkEE6OKfbbS7BY4oTydg',
    appId: '1:349106303392:web:ff006a6f9da52ad4e7b4c5',
    messagingSenderId: '349106303392',
    projectId: 'fooddeliveryapp-189af',
    authDomain: 'fooddeliveryapp-189af.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-189af.firebasestorage.app',
    measurementId: 'G-SG8XHHXR4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcWiIXcbJubL9WrTqAoTer7J8tB_Y3nRE',
    appId: '1:349106303392:android:2a40674cb17b4419e7b4c5',
    messagingSenderId: '349106303392',
    projectId: 'fooddeliveryapp-189af',
    storageBucket: 'fooddeliveryapp-189af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7horxTLAyiiElGClClkh80u5vCpddRvU',
    appId: '1:349106303392:ios:42135f25ad1c7befe7b4c5',
    messagingSenderId: '349106303392',
    projectId: 'fooddeliveryapp-189af',
    storageBucket: 'fooddeliveryapp-189af.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7horxTLAyiiElGClClkh80u5vCpddRvU',
    appId: '1:349106303392:ios:42135f25ad1c7befe7b4c5',
    messagingSenderId: '349106303392',
    projectId: 'fooddeliveryapp-189af',
    storageBucket: 'fooddeliveryapp-189af.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKOQauHtjpvSJHkEE6OKfbbS7BY4oTydg',
    appId: '1:349106303392:web:d795c8cc0d4f8c59e7b4c5',
    messagingSenderId: '349106303392',
    projectId: 'fooddeliveryapp-189af',
    authDomain: 'fooddeliveryapp-189af.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-189af.firebasestorage.app',
    measurementId: 'G-L46ZWVV926',
  );
}
